name: Security vulnerability scan

on:
    workflow_dispatch:
    pull_request:

jobs:
    scan:
        name: Secscan
        uses: canonical/observability/.github/workflows/rock-sec-scan.yaml@feat/secscan-test
        secrets: inherit
        with:
          rock-name: "ubuntu/tempo"
          rock-version: 2-24.04
