name: Update rock

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update:
    name: Update rock
    uses: canonical/observability/.github/workflows/rock-update.yaml@0aac30b0842d2c7c6258809d0ea8509cc890fddc
    secrets: inherit
    with:
      source-repo: grafana/tempo
